# Generated by Django 2.0 on 2020-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('bag', models.CharField(default='', max_length=200)),
                ('materialChecked2', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('bleachwhites', models.CharField(max_length=200)),
                ('deliverydate', models.CharField(default='', max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('item', models.CharField(default='', max_length=200)),
                ('laundry', models.CharField(default='', max_length=200)),
                ('pickupdate', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('price2', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pricing',
            },
        ),
    ]
